### PR TITLE
added log max size & backup count

### LINKED ISSUE #8: Rotation issues with utbox.log
Hi,
I have a SHC that the utbox.log file in `$SPLUNK_HOME//var/log/splunk` is getting very large (10Gb+) and causing disk space issues.  Is there any log rotation setup for this file. Other TA log files in this directory rotate to a `*.log.1` or such file and then get delete but that doesnt seem to happen for this file.  This is really an issue since it seems that its set to [debug](https://github.com/splunk/utbox/blob/e2330a0254d4d8011bcc230d0ef1a0da982c7b8f/utbox/bin/ut_log.py#L7) by default with no way to change the logging level.

### PR DESCRIPTION
**Pull request by satellite-no**
Added maxBytes & backupCount to stop the log from from growing out of control and consuming all of the disk space.  Note this is best practice to include per https://docs.python.org/3/library/logging.handlers.html#logging.handlers.RotatingFileHandler.

Closes #8

### CODE REVIEW

**Comment by satellite-no** [comment]
@dfederschmidt could you take a look at this PR.

**Comment by dfederschmidt** [comment]
@satellite-no  Thanks for opening the PR and reporting this issue. I moved teams internally and am not able to release this app on my own anymore. I forwarded this to the appropriate person to take a look. Thanks again!

**Comment by mayurah** [comment]
@dfederschmidt @ggokdemir can test this change, and we can get this merged soon.

**Comment by ggokdemir** [comment]
@satellite-no I'll have a look. Thanks for your help!

**Review by ggokdemir — APPROVED** [review]
Looks good to me. 
ref = https://docs.python.org/3/library/logging.handlers.html

**Pull request merged**
